# Generated by Django 5.1.4 on 2024-12-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_profilepic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dafault.png', upload_to='user_pics'),
        ),
    ]
